# Generated by Django 5.1.7 on 2025-03-08 17:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireNOCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_address', models.CharField(max_length=255)),
                ('fire_extinguisher', cloudinary.models.CloudinaryField(max_length=255, verbose_name='fire_noc')),
                ('fire_exit', cloudinary.models.CloudinaryField(max_length=255, verbose_name='fire_noc')),
                ('fire_safety_sign', cloudinary.models.CloudinaryField(max_length=255, verbose_name='fire_noc')),
                ('water_infrastructure', cloudinary.models.CloudinaryField(max_length=255, verbose_name='fire_noc')),
            ],
        ),
    ]
