# Generated by Django 5.1.7 on 2025-03-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_noc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firenocsubmission',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='firenocsubmission',
            name='name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='firenocsubmission',
            name='org_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='firenocsubmission',
            name='phone',
            field=models.CharField(default='Unknown', max_length=13),
        ),
    ]
