# Generated by Django 5.1.7 on 2025-03-09 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_noc', '0003_rename_site_address_firenocsubmission_org_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='firenocsubmission',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
