# Generated by Django 5.1.7 on 2025-03-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_noc', '0004_firenocsubmission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='firenocsubmission',
            name='noc_pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
