# Generated by Django 5.1.7 on 2025-03-17 16:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_noc', '0005_firenocsubmission_noc_pdf_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firenocsubmission',
            name='noc_pdf_url',
        ),
        migrations.AddField(
            model_name='firenocsubmission',
            name='noc_pdf',
            field=models.FileField(blank=True, null=True, upload_to='fire_noc_pdfs/'),
        ),
        migrations.AlterField(
            model_name='firenocsubmission',
            name='fire_exit',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='fire_noc_images'),
        ),
        migrations.AlterField(
            model_name='firenocsubmission',
            name='fire_extinguisher',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='fire_noc_images'),
        ),
        migrations.AlterField(
            model_name='firenocsubmission',
            name='fire_safety_sign',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='fire_noc_images'),
        ),
        migrations.AlterField(
            model_name='firenocsubmission',
            name='water_infrastructure',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='fire_noc_images'),
        ),
    ]
