# Generated by Django 5.1.7 on 2025-03-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_noc', '0006_remove_firenocsubmission_noc_pdf_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firenocsubmission',
            name='noc_pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
