# Generated by Django 5.1.7 on 2025-03-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_noc', '0007_firenocsubmission_noc_pdf_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firenocsubmission',
            name='noc_pdf',
        ),
    ]
