# Generated by Django 5.1.7 on 2025-03-17 16:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_noc', '0008_remove_firenocsubmission_noc_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firenocsubmission',
            name='fire_exit',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='fire_noc'),
        ),
        migrations.AlterField(
            model_name='firenocsubmission',
            name='fire_extinguisher',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='fire_noc'),
        ),
        migrations.AlterField(
            model_name='firenocsubmission',
            name='fire_safety_sign',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='fire_noc'),
        ),
        migrations.AlterField(
            model_name='firenocsubmission',
            name='water_infrastructure',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='fire_noc'),
        ),
    ]
